import { Book } from './types';

export const mockBooks: Book[] = [
  // Anatomy (existing)
  {
    id: '1',
    title: "Gray's Anatomy for Students",
    author: 'Richard Drake, A. Wayne Vogl, Adam W. M. Mitchell',
    category: 'Anatomy',
    coverUrl: '/books/grays-anatomy.jpg',
  },
  {
    id: '4',
    title: "Netter's Atlas of Human Anatomy",
    author: 'Frank H. Netter',
    category: 'Anatomy',
    coverUrl: '/books/netter.jpg',
  },
  {
    id: '51',
    title: "Moore's Clinically Oriented Anatomy",
    author: 'Keith L. Moore, Arthur F. Dalley, Anne M. R. Agur',
    category: 'Anatomy',
    coverUrl: '/books/grays-anatomy.jpg',
  },
  {
    id: '52',
    title: "Clinically Oriented Anatomy",
    author: 'Keith L. Moore, Arthur F. Dalley',
    category: 'Anatomy',
    coverUrl: '/books/grays-anatomy.jpg',
  },
  {
    id: '53',
    title: "Last's Anatomy: Regional and Applied",
    author: 'John W. Adams, Peter H. Abrahams',
    category: 'Anatomy',
    coverUrl: '/books/netter.jpg',
  },

  // Internal Medicine (existing)
  {
    id: '2',
    title: "Harrison's Principles of Internal Medicine",
    author: 'Dennis Kasper, Anthony Fauci, Stephen Hauser',
    category: 'Internal Medicine',
    coverUrl: '/books/harrisons.jpg',
  },
  {
    id: '54',
    title: "Davidson's Principles and Practice of Medicine",
    author: 'Sarah J. Finlay, Edwin A. B. Hughes',
    category: 'Internal Medicine',
    coverUrl: '/books/harrisons.jpg',
  },
  {
    id: '55',
    title: "Kumar and Clark's Clinical Medicine",
    author: 'Parveen Kumar, Michael Clark',
    category: 'Internal Medicine',
    coverUrl: '/books/harrisons.jpg',
  },
  {
    id: '56',
    title: "Oxford Textbook of Medicine",
    author: 'D. A. Warrell, T. J. A. Cox, J. D. Firth',
    category: 'Internal Medicine',
    coverUrl: '/books/harrisons.jpg',
  },
  {
    id: '57',
    title: "Cecil Textbook of Medicine",
    author: 'Russell L. Cecil, J. Claude Bennett',
    category: 'Internal Medicine',
    coverUrl: '/books/harrisons.jpg',
  },

  // Pathology (existing)
  {
    id: '3',
    title: 'Robbins and Cotran Pathologic Basis of Disease',
    author: 'Vinay Kumar, Abul K. Abbas, Jon C. Aster',
    category: 'Pathology',
    coverUrl: '/books/robbins.jpg',
  },
  {
    id: '58',
    title: "Robbins Basic Pathology",
    author: 'Vinay Kumar, Abul K. Abbas, Jon C. Aster',
    category: 'Pathology',
    coverUrl: '/books/robbins.jpg',
  },
  {
    id: '59',
    title: "Harsh Mohan Textbook of Pathology",
    author: 'Harsh Mohan',
    category: 'Pathology',
    coverUrl: '/books/robbins.jpg',
  },
  {
    id: '60',
    title: "Rubin's Pathology: Clinicopathologic Foundations of Medicine",
    author: 'Raphael Rubin, David S. Strayer',
    category: 'Pathology',
    coverUrl: '/books/robbins.jpg',
  },
  {
    id: '61',
    title: "Pathologic Basis of Disease",
    author: 'Vinay Kumar',
    category: 'Pathology',
    coverUrl: '/books/robbins.jpg',
  },

  // Physiology (existing)
  {
    id: '5',
    title: 'Guyton and Hall Textbook of Medical Physiology',
    author: 'John E. Hall',
    category: 'Physiology',
    coverUrl: '/books/guyton.jpg',
  },
  {
    id: '62',
    title: "Ganong's Review of Medical Physiology",
    author: 'Kim E. Barrett, Susan M. Barman, Scott L. Boitano, Heddwen L. Brooks',
    category: 'Physiology',
    coverUrl: '/books/guyton.jpg',
  },
  {
    id: '63',
    title: "Berne and Levy Physiology",
    author: 'Matthew N. Levy, Bruce M. Koeppen, Bruce A. Stanton',
    category: 'Physiology',
    coverUrl: '/books/guyton.jpg',
  },
  {
    id: '64',
    title: "Textbook of Medical Physiology",
    author: 'Arthur C. Guyton, John E. Hall',
    category: 'Physiology',
    coverUrl: '/books/guyton.jpg',
  },
  {
    id: '65',
    title: "Human Physiology: From Cells to Systems",
    author: 'Lauralee Sherwood',
    category: 'Physiology',
    coverUrl: '/books/guyton.jpg',
  },

  // Pharmacology (existing)
  {
    id: '6',
    title: "Katzung & Trevor's Pharmacology: Examination & Board Review",
    author: 'Bertram G. Katzung, Anthony J. Trevor',
    category: 'Pharmacology',
    coverUrl: '/books/katzung.jpg',
  },
  {
    id: '66',
    title: "Goodman and Gilman's The Pharmacological Basis of Therapeutics",
    author: 'Laurence L. Brunton, Randa Hilal-Dandan, Bjorn C. Knollmann',
    category: 'Pharmacology',
    coverUrl: '/books/katzung.jpg',
  },
  {
    id: '67',
    title: "Basic and Clinical Pharmacology",
    author: 'Bertram G. Katzung',
    category: 'Pharmacology',
    coverUrl: '/books/katzung.jpg',
  },
  {
    id: '68',
    title: "Rang and Dale's Pharmacology",
    author: 'James M. Ritter, Lionel D. Lewis, Timothy G. Mant, A. Strieter',
    category: 'Pharmacology',
    coverUrl: '/books/katzung.jpg',
  },
  {
    id: '69',
    title: "Lippincott Illustrated Reviews: Pharmacology",
    author: 'Karen Whalen, Richard A. Harvey, Pamela C. Champe',
    category: 'Pharmacology',
    coverUrl: '/books/katzung.jpg',
  },

  // Biochemistry
  {
    id: '7',
    title: "Lehninger Principles of Biochemistry",
    author: 'David L. Nelson, Michael M. Cox',
    category: 'Biochemistry',
    coverUrl: '/books/grays-anatomy.jpg',
  },
  {
    id: '8',
    title: "Harper's Illustrated Biochemistry",
    author: 'Victor W. Rodwell, David A. Bender, Peter J. Kennelly, P. Anthony Weil',
    category: 'Biochemistry',
    coverUrl: '/books/grays-anatomy.jpg',
  },
  {
    id: '9',
    title: "Lippincott Illustrated Reviews: Biochemistry",
    author: 'Richard A. Harvey, Denise R. Ferrier',
    category: 'Biochemistry',
    coverUrl: '/books/grays-anatomy.jpg',
  },
  {
    id: '10',
    title: "Biochemistry by Voet and Voet",
    author: 'Donald Voet, Judith G. Voet, Charlotte W. Pratt',
    category: 'Biochemistry',
    coverUrl: '/books/grays-anatomy.jpg',
  },
  {
    id: '11',
    title: "Textbook of Biochemistry and Human Biology",
    author: 'G. P. Talwar, L. M. Srivastava',
    category: 'Biochemistry',
    coverUrl: '/books/grays-anatomy.jpg',
  },

  // Embryology
  {
    id: '12',
    title: "Langman's Medical Embryology",
    author: 'Jan Sadler',
    category: 'Embryology',
    coverUrl: '/books/netter.jpg',
  },
  {
    id: '13',
    title: "The Developing Human: Clinically Oriented Embryology",
    author: 'Keith L. Moore, T. V. N. Persaud, Mark G. Torchia',
    category: 'Embryology',
    coverUrl: '/books/netter.jpg',
  },
  {
    id: '14',
    title: "Human Embryology and Developmental Biology",
    author: 'Bruce M. Carlson',
    category: 'Embryology',
    coverUrl: '/books/netter.jpg',
  },
  {
    id: '15',
    title: "Before We Are Born: Essentials of Embryology and Birth Defects",
    author: 'Keith L. Moore, T. V. N. Persaud, Mark G. Torchia',
    category: 'Embryology',
    coverUrl: '/books/netter.jpg',
  },
  {
    id: '16',
    title: "Medical Embryology",
    author: 'Jan Langman',
    category: 'Embryology',
    coverUrl: '/books/netter.jpg',
  },

  // Cell Biology
  {
    id: '17',
    title: "Molecular Biology of the Cell",
    author: 'Bruce Alberts, Alexander Johnson, Julian Lewis, David Morgan, Martin Raff, Keith Roberts, Peter Walter',
    category: 'Cell Biology',
    coverUrl: '/books/robbins.jpg',
  },
  {
    id: '18',
    title: "The Cell: A Molecular Approach",
    author: 'Geoffrey M. Cooper',
    category: 'Cell Biology',
    coverUrl: '/books/robbins.jpg',
  },
  {
    id: '19',
    title: "Essential Cell Biology",
    author: 'Bruce Alberts, Dennis Bray, Karen Hopkin, Alexander Johnson, Julian Lewis, Martin Raff, Keith Roberts, Peter Walter',
    category: 'Cell Biology',
    coverUrl: '/books/robbins.jpg',
  },
  {
    id: '20',
    title: "Molecular Cell Biology",
    author: 'Harvey Lodish, Arnold Berk, S. Lawrence Zipursky, Paul Matsudaira, David Baltimore, James Darnell',
    category: 'Cell Biology',
    coverUrl: '/books/robbins.jpg',
  },
  {
    id: '21',
    title: "Cell and Molecular Biology: Concepts and Experiments",
    author: 'Gerald Karp',
    category: 'Cell Biology',
    coverUrl: '/books/robbins.jpg',
  },

  // Genetics
  {
    id: '22',
    title: "Thompson and Thompson Genetics in Medicine",
    author: 'Robert L. Nussbaum, Roderick R. McInnes, Huntington F. Willard',
    category: 'Genetics',
    coverUrl: '/books/harrisons.jpg',
  },
  {
    id: '23',
    title: "Genetics: Analysis and Principles",
    author: 'Robert J. Brooker',
    category: 'Genetics',
    coverUrl: '/books/harrisons.jpg',
  },
  {
    id: '24',
    title: "Human Molecular Genetics",
    author: 'Tom Strachan, Andrew Read',
    category: 'Genetics',
    coverUrl: '/books/harrisons.jpg',
  },
  {
    id: '25',
    title: "Emery's Elements of Medical Genetics",
    author: 'Peter Turnpenny, Sian Ellard',
    category: 'Genetics',
    coverUrl: '/books/harrisons.jpg',
  },
  {
    id: '26',
    title: "Jorde's Medical Genetics",
    author: 'Lynn B. Jorde, John C. Carey, Michael J. Bamshad',
    category: 'Genetics',
    coverUrl: '/books/harrisons.jpg',
  },

  // Parasitology
  {
    id: '27',
    title: "Medical Parasitology",
    author: 'Rohela Mahmud, Yvonne Ai Lian Lim, Amirah Amir',
    category: 'Parasitology',
    coverUrl: '/books/katzung.jpg',
  },
  {
    id: '28',
    title: "Markell and Voge's Medical Parasitology",
    author: 'John T. Marcus, Marianna Wilson',
    category: 'Parasitology',
    coverUrl: '/books/katzung.jpg',
  },
  {
    id: '29',
    title: "Paniker's Textbook of Medical Parasitology",
    author: 'C. K. Jayaram Paniker',
    category: 'Parasitology',
    coverUrl: '/books/katzung.jpg',
  },
  {
    id: '30',
    title: "Foundations of Parasitology",
    author: 'Gerald D. Schmidt, Larry S. Roberts',
    category: 'Parasitology',
    coverUrl: '/books/katzung.jpg',
  },
  {
    id: '31',
    title: "Medical Parasitology",
    author: 'K. D. M. M. D. K. Karunaratne',
    category: 'Parasitology',
    coverUrl: '/books/katzung.jpg',
  },

  // Microbiology
  {
    id: '32',
    title: "Jawetz, Melnick, & Adelberg's Medical Microbiology",
    author: 'Stephen M. Morse, George F. Brooks, Karen C. Carroll, Janet S. Butel',
    category: 'Microbiology',
    coverUrl: '/books/guyton.jpg',
  },
  {
    id: '33',
    title: "Medical Microbiology",
    author: 'Patrick R. Murray, Ken S. Rosenthal, Michael A. Pfaller',
    category: 'Microbiology',
    coverUrl: '/books/guyton.jpg',
  },
  {
    id: '34',
    title: "Ananthanarayan and Paniker's Textbook of Microbiology",
    author: 'G. Ananthanarayan, C. K. Jayaram Paniker',
    category: 'Microbiology',
    coverUrl: '/books/guyton.jpg',
  },
  {
    id: '35',
    title: "Lippincott Illustrated Reviews: Microbiology and Immunology",
    author: 'Richard A. Harvey, Pamela C. Champe, Bruce D. Hostetter',
    category: 'Microbiology',
    coverUrl: '/books/guyton.jpg',
  },
  {
    id: '36',
    title: "Sherris Medical Microbiology",
    author: 'Kenneth J. Ryan, C. George Ray',
    category: 'Microbiology',
    coverUrl: '/books/guyton.jpg',
  },

  // First Aid
  {
    id: '37',
    title: "First Aid for the USMLE Step 1",
    author: 'James S. Yeh, Tao Le, James S. Yeh',
    category: 'First Aid',
    coverUrl: '/books/harrisons.jpg',
  },
  {
    id: '38',
    title: "First Aid for the Basic Sciences: Total Review and Second Look",
    author: 'James S. Yeh, James S. Yeh',
    category: 'First Aid',
    coverUrl: '/books/harrisons.jpg',
  },
  {
    id: '39',
    title: "First Aid for the USMLE Step 2 CK",
    author: 'James S. Yeh, James S. Yeh',
    category: 'First Aid',
    coverUrl: '/books/harrisons.jpg',
  },
  {
    id: '40',
    title: "First Aid for the Basic Sciences: General Principles and Essential Concepts",
    author: 'James S. Yeh',
    category: 'First Aid',
    coverUrl: '/books/harrisons.jpg',
  },
  {
    id: '41',
    title: "First Aid for the USMLE Step 1 2024",
    author: 'James S. Yeh, James S. Yeh',
    category: 'First Aid',
    coverUrl: '/books/harrisons.jpg',
  },

  // Biostatistics
  {
    id: '42',
    title: "Fundamentals of Biostatistics",
    author: 'Bernard Rosner',
    category: 'Biostatistics',
    coverUrl: '/books/robbins.jpg',
  },
  {
    id: '43',
    title: "Biostatistics: A Foundation for Analysis in the Health Sciences",
    author: 'Wayne W. Daniel, Chad L. Cross',
    category: 'Biostatistics',
    coverUrl: '/books/robbins.jpg',
  },
  {
    id: '44',
    title: "Medical Biostatistics",
    author: 'Abhaya Indrayan, Rajeev K. Malhotra',
    category: 'Biostatistics',
    coverUrl: '/books/robbins.jpg',
  },
  {
    id: '45',
    title: "High-Yield Biostatistics, Epidemiology, and Public Health",
    author: 'Anthony N. Glaser, David A. Elashoff',
    category: 'Biostatistics',
    coverUrl: '/books/robbins.jpg',
  },
  {
    id: '46',
    title: "Practical Biostatistics",
    author: 'Abhaya Indrayan',
    category: 'Biostatistics',
    coverUrl: '/books/robbins.jpg',
  },

  // Immunology
  {
    id: '70',
    title: "Kuby Immunology",
    author: 'Thomas J. Kindt, Richard A. Goldsby, Barbara A. Osborne',
    category: 'Immunology',
    coverUrl: '/books/netter.jpg',
  },
  {
    id: '71',
    title: "Abbas Cellular and Molecular Immunology",
    author: 'Abul K. Abbas, Andrew H. Lichtman, Shiv Pillai',
    category: 'Immunology',
    coverUrl: '/books/netter.jpg',
  },
  {
    id: '72',
    title: "Janeway's Immunobiology",
    author: 'Kenneth Murphy, Casey Weaver',
    category: 'Immunology',
    coverUrl: '/books/netter.jpg',
  },
  {
    id: '73',
    title: "Roitt's Essential Immunology",
    author: 'Peter J. Delves, Seamus J. Martin, David R. Burton, Ivan M. Roitt',
    category: 'Immunology',
    coverUrl: '/books/netter.jpg',
  },
  {
    id: '74',
    title: "Clinical Immunology and Serology in Laboratory Medicine",
    author: 'Christine Dorresteyn Stevens',
    category: 'Immunology',
    coverUrl: '/books/netter.jpg',
  },

  // Neuroscience
  {
    id: '75',
    title: "Principles of Neural Science",
    author: 'Eric Kandel, James Schwartz, Thomas Jessell, Steven Siegelbaum, A. J. Hudspeth',
    category: 'Neuroscience',
    coverUrl: '/books/guyton.jpg',
  },
  {
    id: '76',
    title: "Neuroscience: Exploring the Brain",
    author: 'Mark F. Bear, Barry W. Connors, Michael A. Paradiso',
    category: 'Neuroscience',
    coverUrl: '/books/guyton.jpg',
  },
  {
    id: '77',
    title: "Clinical Neuroanatomy and Neuroscience",
    author: 'Mark J. T. FitzGerald, Gregory Gruener, Estomih Mtui',
    category: 'Neuroscience',
    coverUrl: '/books/guyton.jpg',
  },
  {
    id: '78',
    title: "Neuroanatomy through Clinical Cases",
    author: 'Hal Blumenfeld',
    category: 'Neuroscience',
    coverUrl: '/books/guyton.jpg',
  },
  {
    id: '79',
    title: "Basic Clinical Neuroscience",
    author: 'Mark J. T. FitzGerald',
    category: 'Neuroscience',
    coverUrl: '/books/guyton.jpg',
  },

  // Surgery
  {
    id: '80',
    title: "Bailey & Love's Short Practice of Surgery",
    author: 'R. C. G. Russell, Norman S. Williams, Christopher J. H. Bulstrode',
    category: 'Surgery',
    coverUrl: '/books/harrisons.jpg',
  },
  {
    id: '81',
    title: "Schwartz's Principles of Surgery",
    author: 'F. Charles Brunicardi, Dana L. Stabile, David R. Hunt',
    category: 'Surgery',
    coverUrl: '/books/harrisons.jpg',
  },
  {
    id: '82',
    title: "Sabiston Textbook of Surgery",
    author: 'Courtney M. Townsend, R. Daniel Beauchamp, B. Mark Evers',
    category: 'Surgery',
    coverUrl: '/books/harrisons.jpg',
  },
  {
    id: '83',
    title: "Oxford Handbook of Clinical Surgery",
    author: 'Gordon G. Macfarlane, Peter J. Holt, John D. Reed',
    category: 'Surgery',
    coverUrl: '/books/harrisons.jpg',
  },
  {
    id: '84',
    title: "Essential Clinical Anatomy",
    author: 'Keith L. Moore, Arthur F. Dalley',
    category: 'Surgery',
    coverUrl: '/books/harrisons.jpg',
  },

  // Pediatrics
  {
    id: '85',
    title: "Nelson Textbook of Pediatrics",
    author: 'Robert M. Kliegman, Bonita F. D. Stanton, Joseph St. Geme, Nina F. Schor, Richard E. Behrman',
    category: 'Pediatrics',
    coverUrl: '/books/katzung.jpg',
  },
  {
    id: '86',
    title: "Textbook of Pediatrics",
    author: 'O. P. Ghai',
    category: 'Pediatrics',
    coverUrl: '/books/katzung.jpg',
  },
  {
    id: '87',
    title: "Pediatrics: A Clinical Guide",
    author: 'Karen Marcdante, Robert M. Kliegman',
    category: 'Pediatrics',
    coverUrl: '/books/katzung.jpg',
  },
  {
    id: '88',
    title: "Current Diagnosis & Treatment: Pediatrics",
    author: 'William W. Hay, Myron J. Levin, Judith M. Sondheimer, Judith W. Ross',
    category: 'Pediatrics',
    coverUrl: '/books/katzung.jpg',
  },
  {
    id: '89',
    title: "Essentials of Pediatrics",
    author: 'O. P. Ghai',
    category: 'Pediatrics',
    coverUrl: '/books/katzung.jpg',
  },

  // Obstetrics & Gynecology
  {
    id: '90',
    title: "Williams Obstetrics",
    author: 'F. Gary Cunningham, Kenneth J. Leveno, Steven L. Bloom, Jodi S. Dashe, Barbara M. Hoffman, Brian L. Casey, Catherine Y. Spong',
    category: 'Obstetrics & Gynecology',
    coverUrl: '/books/grays-anatomy.jpg',
  },
  {
    id: '91',
    title: "Williams Gynecology",
    author: 'John R. Schorge, Joseph I. Schaffer, Barbara L. Hoffman, Courtney M. Schume, Karen D. Bradshaw, David D. Im',
    category: 'Obstetrics & Gynecology',
    coverUrl: '/books/grays-anatomy.jpg',
  },
  {
    id: '92',
    title: "Danforth's Obstetrics and Gynecology",
    author: 'Ronald S. Gibbs, Beth Y. Karlan, Philip J. Haney, Isaac E. Nygaard',
    category: 'Obstetrics & Gynecology',
    coverUrl: '/books/grays-anatomy.jpg',
  },
  {
    id: '93',
    title: "Comprehensive Gynecology",
    author: 'John R. Schorge, Joseph I. Schaffer, Barbara L. Hoffman',
    category: 'Obstetrics & Gynecology',
    coverUrl: '/books/grays-anatomy.jpg',
  },
  {
    id: '94',
    title: "Textbook of Obstetrics",
    author: 'Dutta DC',
    category: 'Obstetrics & Gynecology',
    coverUrl: '/books/grays-anatomy.jpg',
  },

  // Psychiatry
  {
    id: '95',
    title: "Kaplan and Sadock's Synopsis of Psychiatry",
    author: 'Benjamin J. Sadock, Virginia A. Sadock, Pedro Ruiz',
    category: 'Psychiatry',
    coverUrl: '/books/robbins.jpg',
  },
  {
    id: '96',
    title: "The American Psychiatric Association Publishing Textbook of Psychiatry",
    author: 'Laura Weiss Roberts, Allan Tasman, Jerald Kay, Jeffrey A. Lieberman, John A. Talbott',
    category: 'Psychiatry',
    coverUrl: '/books/robbins.jpg',
  },
  {
    id: '97',
    title: "Oxford Textbook of Psychiatry",
    author: 'Paul Harrison, Philip Cowen, Crispin Taylor, John Geddes',
    category: 'Psychiatry',
    coverUrl: '/books/robbins.jpg',
  },
  {
    id: '98',
    title: "Shorter Oxford Textbook of Psychiatry",
    author: 'Paul Harrison, Philip Cowen, Crispin Taylor',
    category: 'Psychiatry',
    coverUrl: '/books/robbins.jpg',
  },
  {
    id: '99',
    title: "Psychiatry",
    author: 'Allan Tasman, Jerald Kay, Jeffrey A. Lieberman, John A. Talbott, Laura Weiss Roberts',
    category: 'Psychiatry',
    coverUrl: '/books/robbins.jpg',
  },
];
